name: krc
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - optuna=4.2.1
  - optuna-dashboard=0.18.0
  - pip:
      - keras==3.9.2
      - tensorflow==2.18.0
      - numpy==2.0.2
      - scipy==1.14.1
      - pandas==2.2.3
      - networkx==3.4.2
      - natsort==8.4.0
      - matplotlib==3.9.2
      - netCDF4==1.7.2
      - xarray==2025.1.1
      - rich==14.0.0
      - ipykernel==6.29.5
      - ipywidgets==8.1.5
      - ipympl==0.9.4
