name: ESN
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-forge/linux-64::_libgcc_mutex==0.1=conda_forge
  - conda-forge/linux-64::ca-certificates==2024.8.30=hbcca054_0
  - conda-forge/noarch::cuda-version==12.6=h7480c83_3
  - defaults/linux-64::ld_impl_linux-64==2.38=h1181459_1
  - conda-forge/linux-64::python_abi==3.10=5_cp310
  - defaults/noarch::tzdata==2024a=h04d1e81_0
  - conda-forge/linux-64::cuda-crt-tools==12.6.68=ha770c72_0
  - conda-forge/noarch::cuda-cudart_linux-64==12.6.68=h3f2d84a_0
  - conda-forge/linux-64::libgomp==14.1.0=h77fa898_1
  - conda-forge/linux-64::_openmp_mutex==4.5=2_gnu
  - conda-forge/linux-64::libgcc==14.1.0=h77fa898_1
  - conda-forge/linux-64::libbrotlicommon==1.1.0=hb9d3cd8_2
  - conda-forge/linux-64::libgcc-ng==14.1.0=h69a702a_1
  - conda-forge/linux-64::libgfortran5==14.1.0=hc5f4f2c_1
  - conda-forge/linux-64::libstdcxx==14.1.0=hc0a3c3a_1
  - conda-forge/linux-64::openssl==3.3.2=hb9d3cd8_0
  - defaults/linux-64::bzip2==1.0.8=h5eee18b_6
  - conda-forge/linux-64::c-ares==1.33.1=heb4867d_0
  - conda-forge/linux-64::cuda-cudart==12.6.68=h5888daf_0
  - conda-forge/linux-64::cuda-cupti==12.6.68=h5888daf_0
  - conda-forge/linux-64::cuda-nvrtc==12.6.68=h5888daf_0
  - conda-forge/linux-64::cuda-nvtx==12.6.68=h5888daf_0
  - conda-forge/linux-64::cuda-nvvm-tools==12.6.68=he02047a_0
  - conda-forge/linux-64::giflib==5.2.2=hd590300_0
  - conda-forge/linux-64::keyutils==1.6.1=h166bdaf_0
  - conda-forge/linux-64::libbrotlidec==1.1.0=hb9d3cd8_2
  - conda-forge/linux-64::libbrotlienc==1.1.0=hb9d3cd8_2
  - conda-forge/linux-64::libcufft==11.2.6.59=h5888daf_0
  - conda-forge/linux-64::libcurand==10.3.7.68=h5888daf_0
  - conda-forge/linux-64::libdeflate==1.21=h4bc722e_0
  - conda-forge/linux-64::libev==4.33=hd590300_2
  - conda-forge/linux-64::libgfortran==14.1.0=h69a702a_1
  - conda-forge/linux-64::libjpeg-turbo==3.0.0=hd590300_1
  - conda-forge/linux-64::libnsl==2.0.1=hd590300_0
  - conda-forge/linux-64::libnvjitlink==12.6.68=h5888daf_0
  - conda-forge/linux-64::libsodium==1.0.20=h4ab18f5_0
  - conda-forge/linux-64::libstdcxx-ng==14.1.0=h4852527_1
  - conda-forge/linux-64::libuuid==2.38.1=h0b41bf4_0
  - conda-forge/linux-64::libwebp-base==1.4.0=hd590300_0
  - conda-forge/linux-64::libxcrypt==4.4.36=hd590300_1
  - conda-forge/linux-64::libzlib==1.3.1=h4ab18f5_1
  - defaults/linux-64::ncurses==6.4=h6a678d5_0
  - conda-forge/linux-64::pthread-stubs==0.4=h36c2ea0_1001
  - conda-forge/linux-64::xorg-libxau==1.0.11=hd590300_0
  - conda-forge/linux-64::xorg-libxdmcp==1.1.3=h7f98852_0
  - defaults/linux-64::xz==5.4.6=h5eee18b_1
  - conda-forge/linux-64::yaml==0.2.5=h7f98852_2
  - conda-forge/linux-64::brotli-bin==1.1.0=hb9d3cd8_2
  - conda-forge/linux-64::cuda-nvcc-tools==12.6.68=he02047a_0
  - conda-forge/linux-64::flatbuffers==24.3.25=h59595ed_0
  - conda-forge/linux-64::icu==75.1=he02047a_0
  - conda-forge/linux-64::lerc==4.0.0=h27087fc_0
  - conda-forge/linux-64::libabseil==20240116.2=cxx17_he02047a_1
  - conda-forge/linux-64::libaec==1.1.3=h59595ed_0
  - conda-forge/linux-64::libcublas==12.6.1.4=h5888daf_0
  - conda-forge/linux-64::libcusparse==12.5.3.3=h5888daf_0
  - conda-forge/linux-64::libedit==3.1.20191231=he28a2e2_2
  - defaults/linux-64::libffi==3.4.4=h6a678d5_1
  - conda-forge/linux-64::libgfortran-ng==14.1.0=h69a702a_1
  - conda-forge/linux-64::libnghttp2==1.58.0=h47da74e_1
  - conda-forge/linux-64::libpng==1.6.44=hadc24fc_0
  - conda-forge/linux-64::libsqlite==3.46.1=hadc24fc_0
  - conda-forge/linux-64::libssh2==1.11.0=h0841786_0
  - conda-forge/linux-64::libxcb==1.16=hb9d3cd8_1
  - conda-forge/linux-64::nccl==2.22.3.1=hbc370b7_1
  - conda-forge/linux-64::qhull==2020.2=h434a139_5
  - defaults/linux-64::readline==8.2=h5eee18b_0
  - conda-forge/linux-64::snappy==1.2.1=ha2e4443_0
  - conda-forge/linux-64::tk==8.6.13=noxft_h4845f30_101
  - conda-forge/linux-64::zlib==1.3.1=h4ab18f5_1
  - conda-forge/linux-64::zstd==1.5.6=ha6fb4c9_0
  - conda-forge/linux-64::brotli==1.1.0=hb9d3cd8_2
  - conda-forge/linux-64::cudnn==9.2.1.18=hbc370b7_0
  - conda-forge/linux-64::freetype==2.12.1=h267a509_2
  - conda-forge/linux-64::krb5==1.21.3=h659f571_0
  - conda-forge/linux-64::libcusolver==11.6.4.69=h5888daf_0
  - conda-forge/linux-64::libopenblas==0.3.27=pthreads_hac2b453_1
  - conda-forge/linux-64::libprotobuf==4.25.3=h08a7969_0
  - conda-forge/linux-64::libre2-11==2023.09.01=h5a48ba9_2
  - conda-forge/linux-64::libtiff==4.6.0=h46a8edc_4
  - conda-forge/linux-64::python==3.10.13=hd12c33a_1_cpython
  - conda-forge/linux-64::sqlite==3.32.3=hcee41ef_1
  - conda-forge/noarch::absl-py==2.1.0=pyhd8ed1ab_0
  - conda-forge/linux-64::brotli-python==1.1.0=py310hf71b8c6_2
  - conda-forge/noarch::cached_property==1.5.2=pyha770c72_1
  - conda-forge/noarch::certifi==2024.8.30=pyhd8ed1ab_0
  - conda-forge/noarch::charset-normalizer==3.3.2=pyhd8ed1ab_0
  - conda-forge/noarch::colorama==0.4.6=pyhd8ed1ab_0
  - conda-forge/linux-64::colorlog==6.8.2=py310hff52083_1
  - conda-forge/noarch::cycler==0.12.1=pyhd8ed1ab_0
  - conda-forge/linux-64::debugpy==1.8.5=py310hf71b8c6_1
  - conda-forge/noarch::decorator==5.1.1=pyhd8ed1ab_0
  - conda-forge/linux-64::dm-tree==0.1.8=py310h0e2eeba_5
  - conda-forge/noarch::exceptiongroup==1.2.2=pyhd8ed1ab_0
  - conda-forge/noarch::executing==2.1.0=pyhd8ed1ab_0
  - conda-forge/noarch::gast==0.5.5=pyhd8ed1ab_0
  - conda-forge/linux-64::greenlet==3.1.0=py310hf71b8c6_2
  - conda-forge/noarch::hpack==4.0.0=pyh9f0ad1d_0
  - conda-forge/noarch::hyperframe==6.0.1=pyhd8ed1ab_0
  - conda-forge/noarch::idna==3.10=pyhd8ed1ab_0
  - conda-forge/noarch::jupyterlab_widgets==3.0.13=pyhd8ed1ab_0
  - conda-forge/linux-64::kiwisolver==1.4.7=py310h3788b33_0
  - conda-forge/linux-64::lcms2==2.16=hb7c19ff_0
  - conda-forge/linux-64::libblas==3.9.0=23_linux64_openblas
  - conda-forge/linux-64::libcurl==8.10.0=hbbe4b11_0
  - conda-forge/linux-64::markupsafe==2.1.5=py310ha75aee5_1
  - conda-forge/noarch::mdurl==0.1.2=pyhd8ed1ab_0
  - conda-forge/noarch::munkres==1.1.4=pyh9f0ad1d_0
  - conda-forge/noarch::namex==0.0.8=pyhd8ed1ab_0
  - conda-forge/noarch::nest-asyncio==1.6.0=pyhd8ed1ab_0
  - conda-forge/noarch::networkx==3.3=pyhd8ed1ab_1
  - conda-forge/linux-64::openjpeg==2.5.2=h488ebb8_0
  - conda-forge/noarch::packaging==24.1=pyhd8ed1ab_0
  - conda-forge/noarch::parso==0.8.4=pyhd8ed1ab_0
  - conda-forge/noarch::pickleshare==0.7.5=py_1003
  - conda-forge/noarch::platformdirs==4.3.3=pyhd8ed1ab_0
  - conda-forge/linux-64::psutil==6.0.0=py310ha75aee5_1
  - conda-forge/noarch::ptyprocess==0.7.0=pyhd3deb0d_0
  - conda-forge/noarch::pure_eval==0.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::pycparser==2.22=pyhd8ed1ab_0
  - conda-forge/noarch::pygments==2.18.0=pyhd8ed1ab_0
  - conda-forge/noarch::pyparsing==3.1.4=pyhd8ed1ab_0
  - conda-forge/noarch::pysocks==1.7.1=pyha2e5f31_6
  - conda-forge/noarch::python-flatbuffers==24.3.25=pyh59ac667_0
  - conda-forge/noarch::python-tzdata==2024.1=pyhd8ed1ab_0
  - conda-forge/noarch::pytz==2024.2=pyhd8ed1ab_0
  - conda-forge/linux-64::pyyaml==6.0.2=py310ha75aee5_1
  - conda-forge/linux-64::re2==2023.09.01=h7f4b329_2
  - defaults/linux-64::setuptools==72.1.0=py310h06a4308_0
  - conda-forge/noarch::six==1.16.0=pyh6c4a22f_0
  - conda-forge/linux-64::tensorboard-data-server==0.7.0=py310h75e40e8_1
  - conda-forge/noarch::termcolor==2.4.0=pyhd8ed1ab_0
  - conda-forge/noarch::threadpoolctl==3.5.0=pyhc1e730c_0
  - conda-forge/linux-64::tornado==6.4.1=py310ha75aee5_1
  - conda-forge/noarch::traitlets==5.14.3=pyhd8ed1ab_0
  - conda-forge/noarch::typing_extensions==4.12.2=pyha770c72_0
  - conda-forge/linux-64::unicodedata2==15.1.0=py310h2372a71_0
  - conda-forge/noarch::wcwidth==0.2.13=pyhd8ed1ab_0
  - defaults/linux-64::wheel==0.44.0=py310h06a4308_0
  - conda-forge/noarch::widgetsnbextension==4.0.13=pyhd8ed1ab_0
  - conda-forge/linux-64::wrapt==1.16.0=py310ha75aee5_1
  - conda-forge/linux-64::zeromq==4.3.5=ha4adb4c_5
  - conda-forge/noarch::zipp==3.20.2=pyhd8ed1ab_0
  - conda-forge/noarch::asttokens==2.4.1=pyhd8ed1ab_0
  - conda-forge/noarch::astunparse==1.6.3=pyhd8ed1ab_0
  - conda-forge/noarch::cached-property==1.5.2=hd8ed1ab_1
  - conda-forge/linux-64::cffi==1.17.1=py310h8deb56e_0
  - conda-forge/noarch::comm==0.2.2=pyhd8ed1ab_0
  - conda-forge/linux-64::fonttools==4.53.1=py310ha75aee5_1
  - conda-forge/noarch::google-pasta==0.2.0=pyhd8ed1ab_1
  - conda-forge/noarch::h2==4.1.0=pyhd8ed1ab_0
  - conda-forge/linux-64::hdf5==1.14.3=nompi_hdf9ad27_105
  - conda-forge/noarch::importlib-metadata==8.5.0=pyha770c72_0
  - conda-forge/noarch::importlib_resources==6.4.5=pyhd8ed1ab_0
  - conda-forge/noarch::jedi==0.19.1=pyhd8ed1ab_0
  - conda-forge/noarch::joblib==1.4.2=pyhd8ed1ab_0
  - conda-forge/linux-64::jupyter_core==5.7.2=py310hff52083_0
  - conda-forge/linux-64::libcblas==3.9.0=23_linux64_openblas
  - conda-forge/linux-64::libgrpc==1.62.2=h15f2491_0
  - conda-forge/linux-64::liblapack==3.9.0=23_linux64_openblas
  - conda-forge/noarch::markdown-it-py==3.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::matplotlib-inline==0.1.7=pyhd8ed1ab_0
  - conda-forge/noarch::pexpect==4.9.0=pyhd8ed1ab_0
  - conda-forge/linux-64::pillow==10.4.0=py310he228d35_1
  - defaults/linux-64::pip==24.2=py310h06a4308_0
  - conda-forge/noarch::prompt-toolkit==3.0.47=pyha770c72_0
  - conda-forge/linux-64::protobuf==4.25.3=py310h0e2eeba_1
  - conda-forge/noarch::python-dateutil==2.9.0=pyhd8ed1ab_0
  - conda-forge/linux-64::pyzmq==26.2.0=py310h71f11fc_2
  - conda-forge/noarch::tqdm==4.66.5=pyhd8ed1ab_0
  - conda-forge/noarch::typing-extensions==4.12.2=hd8ed1ab_0
  - conda-forge/noarch::werkzeug==3.0.4=pyhd8ed1ab_0
  - conda-forge/linux-64::grpcio==1.62.2=py310h1b8f574_0
  - conda-forge/noarch::importlib_metadata==8.5.0=hd8ed1ab_0
  - conda-forge/noarch::mako==1.3.5=pyhd8ed1ab_0
  - conda-forge/noarch::markdown==3.6=pyhd8ed1ab_0
  - conda-forge/linux-64::numpy==1.26.4=py310hb13e2d6_0
  - conda-forge/linux-64::optree==0.12.1=py310h3788b33_1
  - conda-forge/noarch::rich==13.8.1=pyhd8ed1ab_0
  - conda-forge/linux-64::sqlalchemy==2.0.34=py310ha75aee5_1
  - conda-forge/noarch::stack_data==0.6.2=pyhd8ed1ab_0
  - conda-forge/noarch::typeguard==4.3.0=pyhd8ed1ab_1
  - conda-forge/linux-64::zstandard==0.23.0=py310ha39cb0e_1
  - conda-forge/noarch::alembic==1.13.2=pyhd8ed1ab_0
  - conda-forge/linux-64::contourpy==1.3.0=py310h3788b33_1
  - conda-forge/linux-64::h5py==3.11.0=nompi_py310hf054cd7_102
  - conda-forge/noarch::ipython==8.27.0=pyh707e725_0
  - conda-forge/noarch::jupyter_client==8.6.2=pyhd8ed1ab_0
  - conda-forge/linux-64::ml_dtypes==0.4.0=py310h5eaa309_2
  - conda-forge/noarch::opt_einsum==3.3.0=pyhc1e730c_2
  - conda-forge/linux-64::pandas==2.2.2=py310hf9f9076_1
  - conda-forge/noarch::patsy==0.5.6=pyhd8ed1ab_0
  - conda-forge/linux-64::scipy==1.14.1=py310ha3fb0e1_0
  - conda-forge/noarch::tensorboard==2.17.1=pyhd8ed1ab_0
  - conda-forge/noarch::urllib3==2.2.3=pyhd8ed1ab_0
  - conda-forge/noarch::ipykernel==6.29.5=pyh3099207_0
  - conda-forge/noarch::ipywidgets==8.1.5=pyhd8ed1ab_0
  - conda-forge/noarch::keras==3.5.0=pyhd8ed1ab_1
  - conda-forge/linux-64::matplotlib-base==3.9.2=py310h68603db_1
  - conda-forge/noarch::optuna==4.0.0=pyhd8ed1ab_0
  - conda-forge/noarch::requests==2.32.3=pyhd8ed1ab_0
  - conda-forge/linux-64::scikit-learn==1.5.2=py310h27f47ee_1
  - conda-forge/linux-64::statsmodels==0.14.3=py310hf462985_0
  - conda-forge/noarch::seaborn-base==0.13.2=pyhd8ed1ab_2
  - conda-forge/linux-64::tensorflow-base==2.17.0=cuda120py310hdd86fba_202
  - conda-forge/noarch::seaborn==0.13.2=hd8ed1ab_2
  - conda-forge/linux-64::tensorflow-estimator==2.17.0=cuda120py310h1fd330c_202
  - conda-forge/linux-64::tensorflow==2.17.0=cuda120py310heb3ae67_202
  - conda-forge/noarch::keras-core==0.1.7=pyhd8ed1ab_0
  - conda-forge/noarch::keras-tuner==1.4.7=pyhd8ed1ab_0
  - conda-forge/noarch::kt-legacy==1.0.5=pyhd8ed1ab_0
  - xgboost
prefix: /home/elessar/anaconda3/envs/ESN
